server:
  port: 3344
spring:
  application:
    name: springcloud-config-server
  # 连接github远程仓库
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhangzhuowen/springcloud-config.git
          username: zhangzhuowen
          password: Ly729475287